### ISSUE TITLE
configMapKeyRef and secretKeyRef: name and key are inverted

### ISSUE THREAD

**Issue by mnovak1** [xtf-cz/xtf#548]
This MR fixed the `DeploymentConfig` produced by `ContainerBuilder`:
At present key and name are inverted:
```
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql-admin-password
              key: postgresql
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql-password
              key: postgresql
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-user
              key: postgresql
```

with this MR, the correct output is 
```
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql
              key: postgresql-admin-password
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgresql
              key: postgresql-password
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql
              key: postgresql-user
```

Similarly for secretKeyRef.
