### ISSUE TITLE
Add "args" to ContainerBuilder

### ISSUE THREAD

**Issue by tommaso-borgato** [xtf-cz/xtf#595]
We need to add "args" to ContainerBuilder in order to have e.g.:

```yaml
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: postgres-sample
spec:
  selector:
    name: postgres-sample
  template:
    metadata:
      name: postgres-sample
      labels:
        name: postgres-sample
    spec:
      containers:
        - name: postgres-sample
          image: 'quay.io/tborgato/postgres:16'
          args:
            - '-c'
            - shared_buffers=256MB
            - '-c'
            - max_connections=200
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: sampledb
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
```
